title: "StoreClass"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

sidebar:
  - title: "User Guide"
    url: "/docs/UserGuide"
    toc: true
  - title: "Developer Guide"
    url: "/docs/DeveloperGuide"
    toc: true
  - title: "About Us"
    url: "/docs/AboutUs"
    toc: true

markdown: kramdown

repository: "AY2425S1-CS2103T-W10-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
