title: "StoreClass"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

sidebar:
  - title: "User Guide"
    url: UserGuide.html
    toc: true
  - title: "Developer Guide"
    url: DeveloperGuide.html
    toc: true
  - title: "About Us"
    url: AboutUs.html
    toc: false

markdown: kramdown

repository: "Jianwen0451/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
  - jekyll-toc

