title: "StoreClass"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

sidebar:
  - title: "User Guide"
    url: UserGuide.md
    toc: true
  - title: "Developer Guide"
    url: DeveloperGuide.md
    toc: true
  - title: "About Us"
    url: AboutUs.md
    toc: true

markdown: kramdown

repository: "Jianwen0451/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
